name: Skinet
channels:
  - defaults
dependencies:
  - python=3.6
  - pip:
    - cython==0.29.16
    - h5py==2.10.0
    - html5lib==0.9999999
    - imageio==2.8.0
    - imagesize==1.2.0
    - imgaug==0.4.0
    - ipython==7.9.0
    - jsonschema==3.2.0
    - jupyter==1.0.0
    - keras==2.1.6
    - matplotlib==3.0.3
    - numpy==1.18.3
    - opencv-python==4.2.0.34
    - pillow==7.1.1
    - pip==20.0.2
    - scikit-image==0.15.0
    - scipy==1.1.0
    - tensorboard==1.7.0
    - tensorflow-gpu==1.7.0
